; RAM layout for the Pacmo scrolling experiment.
RAM_START:
PLAYER_X:
        DS      1
PLAYER_Y:
        DS      1
ENEMY_X:
        DS      1
ENEMY_Y:
        DS      1
ENEMY_DIR:
        DS      1
ENEMY_TIMER:
        DS      1
ENEMY_PERIOD_CURRENT:
        DS      1
ENEMY_RESPAWN_TIMER:
        DS      1
ENEMY_STATE:
        DS      1
ENEMY2_X:
        DS      1
ENEMY2_Y:
        DS      1
ENEMY2_DIR:
        DS      1
ENEMY2_TIMER:
        DS      1
ENEMY2_RESPAWN_TIMER:
        DS      1
ENEMY2_STATE:
        DS      1
VIEW_X:
        DS      1
VIEW_Y:
        DS      1
MOVE_COOLDOWN:
        DS      1
LAST_KEY:
        DS      1
PACMO_SPLASH_ACTIVE:
        DS      1
HUD_SCAN_INDEX:
        DS      1
SPEAKER_PORT_STATE:
        DS      1
SOUND_TIMER:
        DS      1
PACMO_SCORE:
        DS      2
HUD_SEG_BUFFER:
        DS      6
FRAME_PHASE:
        DS      1
LOGIC_SLICE:
        DS      1
RENDER_EATEN_PTR:
        DS      2
PACMO_POWER_PILLS_EATEN:
        DS      1
PACMO_POWER_TIMER:
        DS      2
PACMO_POWER_TIMER_LO EQU PACMO_POWER_TIMER
PACMO_POWER_TIMER_HI EQU PACMO_POWER_TIMER+1
PACMO_ROUND_COMPLETE:
        DS      1
PACMO_PLAYER_CAUGHT:
        DS      1
PACMO_LEVEL:
        DS      1
PACMO_LEVEL_COMPLETE_GATE:
        DS      2
PACMO_LEVEL_COMPLETE_GATE_LO EQU PACMO_LEVEL_COMPLETE_GATE
PACMO_LEVEL_COMPLETE_GATE_HI EQU PACMO_LEVEL_COMPLETE_GATE+1
PACMO_GAME_OVER_GATE:
        DS      2
PACMO_GAME_OVER_GATE_LO EQU PACMO_GAME_OVER_GATE
PACMO_GAME_OVER_GATE_HI EQU PACMO_GAME_OVER_GATE+1
SCAN_MASK:
        DS      1
SCAN_PTR:
        DS      2
FRAMEBUFFER:
        DS      FRAMEBUFFER_BYTES
FRAMEBUFFER_BACK:
        DS      FRAMEBUFFER_BYTES
PACMO_EATEN_ROWS:
        DS      PACMO_EATEN_BYTES
RAM_END:
