; RAM layout for the Pacmo scrolling experiment.
RAM_START:
PLAYER_X:
        DS      1
PLAYER_Y:
        DS      1
MONSTERS:
MONSTER0:
        DS      MONSTER_SIZE
MONSTER1:
        DS      MONSTER_SIZE
ENEMY_X EQU MONSTER0+MONSTER_X
ENEMY_Y EQU MONSTER0+MONSTER_Y
ENEMY_DIR EQU MONSTER0+MONSTER_DIR
ENEMY_TIMER EQU MONSTER0+MONSTER_TIMER
ENEMY_RESPAWN_TIMER EQU MONSTER0+MONSTER_RESPAWN_TIMER
ENEMY_STATE EQU MONSTER0+MONSTER_STATE
ENEMY2_X EQU MONSTER1+MONSTER_X
ENEMY2_Y EQU MONSTER1+MONSTER_Y
ENEMY2_DIR EQU MONSTER1+MONSTER_DIR
ENEMY2_TIMER EQU MONSTER1+MONSTER_TIMER
ENEMY2_RESPAWN_TIMER EQU MONSTER1+MONSTER_RESPAWN_TIMER
ENEMY2_STATE EQU MONSTER1+MONSTER_STATE
ENEMY_PERIOD_CURRENT:
        DS      1
VIEW_X:
        DS      1
VIEW_Y:
        DS      1
MOVE_COOLDOWN:
        DS      1
LAST_KEY:
        DS      1
PACMO_SPLASH_ACTIVE:
        DS      1
HUD_SCAN_INDEX:
        DS      1
SPEAKER_PORT_STATE:
        DS      1
SOUND_TIMER:
        DS      1
PACMO_SCORE:
        DS      2
HUD_SEG_BUFFER:
        DS      6
FRAME_PHASE:
        DS      1
LOGIC_SLICE:
        DS      1
RENDER_EATEN_PTR:
        DS      2
PACMO_POWER_PILLS_EATEN:
        DS      1
PACMO_POWER_TIMER:
        DS      2
PACMO_POWER_TIMER_LO EQU PACMO_POWER_TIMER
PACMO_POWER_TIMER_HI EQU PACMO_POWER_TIMER+1
PACMO_ROUND_COMPLETE:
        DS      1
PACMO_PLAYER_CAUGHT:
        DS      1
PACMO_LEVEL:
        DS      1
PACMO_LEVEL_COMPLETE_GATE:
        DS      2
PACMO_LEVEL_COMPLETE_GATE_LO EQU PACMO_LEVEL_COMPLETE_GATE
PACMO_LEVEL_COMPLETE_GATE_HI EQU PACMO_LEVEL_COMPLETE_GATE+1
PACMO_GAME_OVER_GATE:
        DS      2
PACMO_GAME_OVER_GATE_LO EQU PACMO_GAME_OVER_GATE
PACMO_GAME_OVER_GATE_HI EQU PACMO_GAME_OVER_GATE+1
SCAN_MASK:
        DS      1
SCAN_PTR:
        DS      2
FRAMEBUFFER:
        DS      FRAMEBUFFER_BYTES
FRAMEBUFFER_BACK:
        DS      FRAMEBUFFER_BYTES
PACMO_EATEN_ROWS:
        DS      PACMO_EATEN_BYTES
RAM_END:
