; RAM layout for the Pacmo scrolling experiment.
RAM_START:
PLAYER_X:
        DB      0
PLAYER_Y:
        DB      0
MONSTERS:
MONSTER0:
        DS      MONSTER_SIZE
MONSTER1:
        DS      MONSTER_SIZE
MONSTER2:
        DS      MONSTER_SIZE
ENEMY_X EQU MONSTER0+MONSTER_X
ENEMY_Y EQU MONSTER0+MONSTER_Y
ENEMY_DIR EQU MONSTER0+MONSTER_DIR
ENEMY_TIMER EQU MONSTER0+MONSTER_TIMER
ENEMY_RESPAWN_TIMER EQU MONSTER0+MONSTER_RESPAWN_TIMER
ENEMY_STATE EQU MONSTER0+MONSTER_STATE
ENEMY2_X EQU MONSTER1+MONSTER_X
ENEMY2_Y EQU MONSTER1+MONSTER_Y
ENEMY2_DIR EQU MONSTER1+MONSTER_DIR
ENEMY2_TIMER EQU MONSTER1+MONSTER_TIMER
ENEMY2_RESPAWN_TIMER EQU MONSTER1+MONSTER_RESPAWN_TIMER
ENEMY2_STATE EQU MONSTER1+MONSTER_STATE
ENEMY3_X EQU MONSTER2+MONSTER_X
ENEMY3_Y EQU MONSTER2+MONSTER_Y
ENEMY3_DIR EQU MONSTER2+MONSTER_DIR
ENEMY3_TIMER EQU MONSTER2+MONSTER_TIMER
ENEMY3_RESPAWN_TIMER EQU MONSTER2+MONSTER_RESPAWN_TIMER
ENEMY3_STATE EQU MONSTER2+MONSTER_STATE
ENEMY_PERIOD_CURRENT:
        DB      0
VIEW_X:
        DB      0
VIEW_Y:
        DB      0
MOVE_COOLDOWN:
        DB      0
LAST_KEY:
        DB      0
PACMO_SPLASH_ACTIVE:
        DB      0
PACMO_PAUSED:
        DB      0
HUD_SCAN_INDEX:
        DB      0
SPEAKER_PORT_STATE:
        DB      0
SOUND_TIMER:
        DB      0
SOUND_DIVIDER_RELOAD:
        DB      0
SOUND_DIVIDER_COUNT:
        DB      0
PACMO_SCORE:
        DW      0
HUD_SEG_BUFFER:
        DS      6
FRAME_PHASE:
        DB      0
LOGIC_SLICE:
        DB      0
RENDER_EATEN_PTR:
        DW      0
PACMO_POWER_PILLS_EATEN:
        DB      0
PACMO_POWER_TIMER:
        DW      0
PACMO_POWER_TIMER_LO EQU PACMO_POWER_TIMER
PACMO_POWER_TIMER_HI EQU PACMO_POWER_TIMER+1
PACMO_ROUND_COMPLETE:
        DB      0
PACMO_PLAYER_CAUGHT:
        DB      0
PACMO_GAME_OVER:
        DB      0
PACMO_LEVEL:
        DB      0
PACMO_LIVES:
        DB      0
PACMO_LEVEL_COMPLETE_GATE:
        DW      0
PACMO_LEVEL_COMPLETE_GATE_LO EQU PACMO_LEVEL_COMPLETE_GATE
PACMO_LEVEL_COMPLETE_GATE_HI EQU PACMO_LEVEL_COMPLETE_GATE+1
PACMO_GAME_OVER_GATE:
        DW      0
PACMO_GAME_OVER_GATE_LO EQU PACMO_GAME_OVER_GATE
PACMO_GAME_OVER_GATE_HI EQU PACMO_GAME_OVER_GATE+1
SCAN_MASK:
        DB      0
SCAN_PTR:
        DW      0
FRAMEBUFFER:
        DS      FRAMEBUFFER_BYTES
FRAMEBUFFER_BACK:
        DS      FRAMEBUFFER_BYTES
PACMO_EATEN_ROWS:
        DS      PACMO_EATEN_BYTES
RAM_END:
